class Consts:
    """constant collection"""
    TOLERANCE = 0.001
    TOLERANCE_SLOPE = 0.1
    
    TRIANGLE_ANGLE_SUM = 180
    
    TRAPEZOID_CHECKER_TRIANGLE_COUNT = 2
    TRAPEZOID_CHECKER_EROSION = 0.5
    TRAPEZOID_OBB_RATIO_BASELINE = 0.6
    
    RECTANGLE_OBB_RATIO_BASELINE = 0.9
    RECTANGLE_ANGLE_SUM = 360
    
    FLAG_OBB_RATIO_BASELINE = 0.7
    
    LONG_SQUARE_SHAPE_ASPECT_RATIO_BASELINE = 1.3